In [44]:
import numpy as np

In [45]:
#ARRAY OPERATIONS

In [46]:
#arithmetic operations

In [47]:
a1 = np.array([1,2,3,4,5])
a2 = np.array([6,7,8,9,10])

In [48]:
a1 + a2 #caution both the sizes must be same

array([ 7,  9, 11, 13, 15])

In [49]:
a1 - a2

array([-5, -5, -5, -5, -5])

In [50]:
a1 * a2

array([ 6, 14, 24, 36, 50])

In [51]:
a1 / a2

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [52]:
a1 // a2

array([0, 0, 0, 0, 0])

In [53]:
a1 ** a2

array([      1,     128,    6561,  262144, 9765625])

In [54]:
#broadcasting

In [55]:
l = [10,20,30,40]
arr  = np.array(l)

In [56]:
#now 

In [57]:
arr+10

array([20, 30, 40, 50])

In [58]:
arr2 = np.arange(1,26).reshape(5,5)
arr2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [59]:
arr2=arr2+10
arr2

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35]])

In [60]:
#deep and shallow copy

In [61]:
#shallow copy
a = np.arange(1,21)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [62]:
slice = a[:5]
slice = slice*10
slice

array([10, 20, 30, 40, 50])

In [63]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [64]:
#deep copy 
b = a.copy()


In [65]:
b[0] = 99 
b

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [66]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [67]:
#matrix operations

In [68]:
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])

In [69]:
A

array([[1, 2],
       [3, 4]])

In [70]:
B

array([[5, 6],
       [7, 8]])

In [71]:
A*B

array([[ 5, 12],
       [21, 32]])

In [72]:
A@B #actuall matrix multplication

array([[19, 22],
       [43, 50]])

In [73]:
np.dot(A,B)

array([[19, 22],
       [43, 50]])

In [74]:
A.T  #transpose 

array([[1, 3],
       [2, 4]])

In [75]:
#advance array manipulaton

In [33]:
#stacking array 

In [34]:
#actualy we can't stack matrices ,we can only stack arrays or vectors 
#and stacking has two types 1) vertical stacking 2) horizontal stacking

In [35]:
a = np.array([1,2,3,4])
b = np.array([6,7,8,9])

In [36]:
np.vstack((a,b))

array([[1, 2, 3, 4],
       [6, 7, 8, 9]])

In [37]:
np.hstack((a,b))

array([1, 2, 3, 4, 6, 7, 8, 9])

In [38]:
np.column_stack((a,b))

array([[1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

In [39]:
#splitting array

In [40]:
c = np.arange(16).reshape(4,4)
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [41]:
np.hsplit(c,4)

[array([[ 0],
        [ 4],
        [ 8],
        [12]]),
 array([[ 1],
        [ 5],
        [ 9],
        [13]]),
 array([[ 2],
        [ 6],
        [10],
        [14]]),
 array([[ 3],
        [ 7],
        [11],
        [15]])]

In [42]:
a=np.vsplit(c,2)
a

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [43]:
for i in a:
    print(i)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]
