In [1]:
import numpy as np

In [2]:
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [3]:
#array indexing anfd slicing of a matrix

In [19]:
arr = np.arange(1,31).reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [30]:
arr[4,4]  #arr[4][4]


np.int64(25)

In [6]:
arr[0:2,1:3]

array([[2, 3],
       [7, 8]])

In [7]:
arr[3:6,3:5]

array([[19, 20],
       [24, 25],
       [29, 30]])

In [8]:
arr[:,2]

array([ 3,  8, 13, 18, 23, 28])

In [9]:
#boolean indexing

In [10]:
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [11]:
bool_index = arr % 2 == 0
bool_index

array([False,  True, False,  True, False,  True, False,  True, False,
        True])