In [1]:
#valid suduko
import numpy as np

In [2]:
import numpy as np

s = np.array([
    [5, 3, 4, 6, 7, 8, 9, 1, 2],
    [6, 7, 2, 1, 9, 5, 3, 4, 8],
    [1, 9, 8, 3, 4, 2, 5, 6, 7],

    [8, 5, 9, 7, 6, 1, 4, 2, 3],
    [4, 2, 6, 8, 5, 3, 7, 9, 1],
    [7, 1, 3, 9, 2, 4, 8, 5, 6],

    [9, 6, 1, 5, 3, 7, 2, 8, 4],
    [2, 8, 7, 4, 1, 9, 6, 3, 5],
    [3, 4, 5, 2, 8, 6, 1, 7, 9]
])

In [3]:
#row_sum 
b = np.sum(s,axis=1) 
for i in b:
    if i != 45:
        print("sudoku is not valid")
        break 
else:
    print("for rows it is valid")

for rows it is valid


In [4]:
c = np.sum(s,axis = 0) 
for j in c:
    if j != 45:
        print("sudoku is not valid")
        break 
else:
    print("for cols it is valid")

for cols it is valid


In [5]:
s[0:3,0:3]

array([[5, 3, 4],
       [6, 7, 2],
       [1, 9, 8]])

In [6]:
s[0:3,3:6]

array([[6, 7, 8],
       [1, 9, 5],
       [3, 4, 2]])

In [7]:
s[0:3,6:9]

array([[9, 1, 2],
       [3, 4, 8],
       [5, 6, 7]])

In [8]:
#similarlly
for i in range(0,9,3):
    for j in range(0,9,3):
        print(s[i:i+3,j:j+3])

[[5 3 4]
 [6 7 2]
 [1 9 8]]
[[6 7 8]
 [1 9 5]
 [3 4 2]]
[[9 1 2]
 [3 4 8]
 [5 6 7]]
[[8 5 9]
 [4 2 6]
 [7 1 3]]
[[7 6 1]
 [8 5 3]
 [9 2 4]]
[[4 2 3]
 [7 9 1]
 [8 5 6]]
[[9 6 1]
 [2 8 7]
 [3 4 5]]
[[5 3 7]
 [4 1 9]
 [2 8 6]]
[[2 8 4]
 [6 3 5]
 [1 7 9]]


In [22]:
for i in range(0,9,3):
    for j in range(0,9,3): 
        n = s[i:i+3,j:j+3]
        print(n.sum())

45
45
45
45
45
45
45
45
45


In [38]:
import numpy as np

# Columns: [Age, Math Marks, Science Marks]
data = np.array([
    [18, 85, 78],   # Student 1
    [19, 92, 88],   # Student 2
    [17, 76, 95],   # Student 3
    [18, 65, 70],   # Student 4
    [20, 91, 85]    # Student 5
])

In [39]:
#get the shape of matrix.
data.shape

(5, 3)

In [40]:
#find the average age of students.
np.mean(data[:,0])

np.float64(18.4)

In [41]:
#exact maths marks of all students.
data[:,1]

array([85, 92, 76, 65, 91])

In [42]:
#find the highest science marks
int(np.max(data[:,2]))

95

In [43]:
#get the details of the student who scored more than 90 marks in Math
data[data[:,1] > 90]

array([[19, 92, 88],
       [20, 91, 85]])

In [16]:
#Increase Math marks of all students by 5 
data[:,1]+=5
data

array([[18, 90, 78],
       [19, 97, 88],
       [17, 81, 95],
       [18, 70, 70],
       [20, 95, 85]])

In [17]:
#find how many students are younger than 19 
len(data[data[:,0] < 19])

3

In [18]:
#calculate the average marks in each subject (column-wise mean).

In [19]:
np.mean(data[:,1:],axis = 0)

array([86.6, 83.2])

In [20]:
#get data of the students who scored at least 80 in both subjects
data[(data[:,1] >= 80) & (data[:,2] >= 80)]

array([[19, 97, 88],
       [17, 81, 95],
       [20, 95, 85]])

In [21]:
#Replace all Science marks < 75 with 0

data[:,2][data[:,2] < 75] = 0
data

array([[18, 90, 78],
       [19, 97, 88],
       [17, 81, 95],
       [18, 70,  0],
       [20, 95, 85]])